build_mode = "release"
target_adapters = ["noir"]
target_platforms = ["react-native"]
react_native = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
]
auto_update = true

[update]
react_native_dest = "../../apps/mobile/modules/mopro"
