#!/usr/bin/env npx tsx
/**
 * Build a Poseidon2 Merkle tree from CSCA certificates.
 *
 * Uses @zkpassport/poseidon2 which matches the Noir poseidon::poseidon2
 * implementation used in our circuits.
 *
 * Leaf = poseidon2Hash([modulus, exponent])
 * Empty leaf = poseidon2Hash([0, 0])
 * Tree depth = 12 (4096 leaves)
 *
 * Outputs:
 *   - tree-root.ts: exports the Merkle root as a bigint
 *   - tree-data.json: cert metadata with leaf hashes for proof generation
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { poseidon2Hash } from "@zkpassport/poseidon2";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TREE_DEPTH = 12;
const NUM_LEAVES = 1 << TREE_DEPTH; // 4096

// BigInt field modulus for BN254
const P = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;

const EMPTY_LEAF = poseidon2Hash([0n, 0n]);

// ---------------------------------------------------------------------------
// Merkle Tree
// ---------------------------------------------------------------------------

function buildTree(leaves: bigint[]): bigint[][] {
  const tree: bigint[][] = [leaves];
  let currentLevel = leaves;

  while (currentLevel.length > 1) {
    const nextLevel: bigint[] = [];
    for (let i = 0; i < currentLevel.length; i += 2) {
      const left = currentLevel[i];
      const right = currentLevel[i + 1] ?? left;
      // Poseidon2 hash of [left, right] — matches Noir's Poseidon2::hash([left, right], 2)
      nextLevel.push(poseidon2Hash([left, right]));
    }
    tree.push(nextLevel);
    currentLevel = nextLevel;
  }

  return tree;
}

function getProof(tree: bigint[][], leafIndex: number): bigint[] {
  const siblings: bigint[] = [];
  let index = leafIndex;

  for (let depth = 0; depth < TREE_DEPTH; depth++) {
    const level = tree[depth];
    const siblingIndex = index % 2 === 0 ? index + 1 : index - 1;
    siblings.push(level[siblingIndex] ?? EMPTY_LEAF);
    index = Math.floor(index / 2);
  }

  return siblings;
}

function verifyProof(leaf: bigint, siblings: bigint[], leafIndex: number): bigint {
  let current = leaf;
  let index = leafIndex;

  for (const sibling of siblings) {
    if (index % 2 === 0) {
      current = poseidon2Hash([current, sibling]);
    } else {
      current = poseidon2Hash([sibling, current]);
    }
    index = Math.floor(index / 2);
  }

  return current;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const certsPath = join(__dirname, "cscas.json");
  const certs: Array<{
    modulus_hex: string;
    exponent: number;
    country: string | null;
    common_name: string | null;
  }> = JSON.parse(readFileSync(certsPath, "utf-8"));

  console.log(`Building Merkle tree from ${certs.length} unique CSCA certs...`);

  // Compute leaf hashes
  const leaves: bigint[] = new Array(NUM_LEAVES).fill(EMPTY_LEAF);

  for (let i = 0; i < certs.length; i++) {
    const mod = BigInt("0x" + certs[i].modulus_hex);
    const exp = BigInt(certs[i].exponent);
    leaves[i] = poseidon2Hash([mod, exp]);
  }

  // Build tree
  console.log("Building tree...");
  const tree = buildTree(leaves);
  const root = tree[tree.length - 1][0];

  console.log(`Tree root: 0x${root.toString(16)}`);
  console.log(`Tree depth: ${TREE_DEPTH}`);
  console.log(`Leaves: ${certs.length} filled, ${NUM_LEAVES - certs.length} empty`);

  // Verify first few proofs
  for (let i = 0; i < Math.min(3, certs.length); i++) {
    const proof = getProof(tree, i);
    const computedRoot = verifyProof(leaves[i], proof, i);
    const match = computedRoot === root;
    console.log(
      `  Proof cert[${i}] (${certs[i].country}): ${match ? "✓ matches" : "✗ mismatch"}`
    );
  }

  // Save root as TypeScript
  const rootTs = `// Auto-generated by build-tree.ts\nexport const CSCA_MERKLE_ROOT = 0x${root.toString(16)}n;\nexport const TREE_DEPTH = ${TREE_DEPTH};\nexport const NUM_CERTS = ${certs.length};\n`;
  writeFileSync(join(__dirname, "tree-root.ts"), rootTs);

  // Save tree data for proof generation
  const treeData = {
    root: `0x${root.toString(16)}`,
    depth: TREE_DEPTH,
    certs: certs.map((cert, i) => ({
      index: i,
      country: cert.country,
      common_name: cert.common_name,
      leaf: `0x${leaves[i].toString(16)}`,
    })),
  };
  writeFileSync(
    join(__dirname, "tree-data.json"),
    JSON.stringify(treeData, null, 2)
  );

  console.log("\nSaved:");
  console.log(`  tree-root.ts`);
  console.log(`  tree-data.json`);
}

main();
