// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test, console2} from "forge-std/Test.sol";
import {BaseUltraHonkVerifier} from "../src/verifiers/BaseUltraHonkVerifier.sol";
import {PrimaryUltraHonkVerifier} from "../src/verifiers/PrimaryUltraHonkVerifier.sol";
import {ProofVerifier} from "../src/ProofVerifier.sol";

/// @notice End-to-end test: real Noir UltraHonk proofs verified on-chain.
/// Proof files generated by `bb prove` from the passport_base and passport_primary circuits.
contract ProofVerifierTest is Test {
    ProofVerifier verifier;
    BaseUltraHonkVerifier baseHonk;
    PrimaryUltraHonkVerifier primaryHonk;

    // Test inputs matching Prover.toml values
    // Base: dg1_hash=1, sod_hash=2, epoch_day=20000
    bytes32 constant EPOCH_NULLIFIER =
        bytes32(uint256(10169623654123766754031260866998371876549336851110854689992825661941566564438));
    bytes32 constant HASHED_ADDRESS = bytes32(uint256(0));
    uint48 constant PASSPORT_EXPIRY = 0;

    // Primary: dg1_hash=1, sod_hash=2, nonce=1
    bytes32 constant NULLIFIER =
        bytes32(uint256(275412644495263924189939344395808058143324727273800689612812660018296150956));
    bytes32 constant NEXT_COMMITMENT =
        bytes32(uint256(19202002815431368995739791825713219422746529042231652773447201800946151423106));

    function setUp() public {
        baseHonk = new BaseUltraHonkVerifier();
        primaryHonk = new PrimaryUltraHonkVerifier();
        verifier = new ProofVerifier(address(baseHonk), address(primaryHonk));
    }

    function test_baseProof_verifiesOnChain() public view {
        bytes memory proof = vm.readFileBinary("test/fixtures/base/proof");
        assertEq(proof.length, 456 * 32, "proof size mismatch");

        bool result = verifier.verifyBaseProof(HASHED_ADDRESS, PASSPORT_EXPIRY, EPOCH_NULLIFIER, proof);
        assertTrue(result, "base proof should verify");
    }

    function test_primaryProof_verifiesOnChain() public view {
        bytes memory proof = vm.readFileBinary("test/fixtures/primary/proof");
        assertEq(proof.length, 456 * 32, "proof size mismatch");

        bool result = verifier.verifyPrimaryProof(HASHED_ADDRESS, PASSPORT_EXPIRY, NULLIFIER, NEXT_COMMITMENT, proof);
        assertTrue(result, "primary proof should verify");
    }

    function test_baseProof_rejectsWrongNullifier() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/base/proof");
        bytes32 wrongNullifier = bytes32(uint256(999));

        vm.expectRevert();
        verifier.verifyBaseProof(HASHED_ADDRESS, PASSPORT_EXPIRY, wrongNullifier, proof);
    }

    function test_primaryProof_rejectsWrongNullifier() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/primary/proof");
        bytes32 wrongNullifier = bytes32(uint256(999));

        vm.expectRevert();
        verifier.verifyPrimaryProof(HASHED_ADDRESS, PASSPORT_EXPIRY, wrongNullifier, NEXT_COMMITMENT, proof);
    }
}
