// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {SigilUltraHonkVerifier} from "../src/verifiers/SigilUltraHonkVerifier.sol";
import {ProofVerifier} from "../src/ProofVerifier.sol";

/// @notice End-to-end test: real Noir UltraHonk proofs verified on-chain.
/// Proof files generated by `bb prove` from the unified sigil circuit.
///
/// Note: These tests require proof files generated from the current circuit version.
/// After circuit changes, regenerate proofs and update test/fixtures/.
contract ProofVerifierTest is Test {
    ProofVerifier verifier;
    SigilUltraHonkVerifier honk;

    function setUp() public {
        honk = new SigilUltraHonkVerifier();
        verifier = new ProofVerifier(address(honk));
    }

    // TODO: Re-enable after regenerating proofs with the unified single-tier circuit.
    // The unified circuit emits 4 public inputs:
    //   [nullifier, epochNullifier, hashed_address, csca_merkle_root]

    function test_stub() public pure {
        // Stub test — remove when proofs are regenerated.
    }
}
