// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IVerificationRegistry
/// @notice Interface for the ZK Passport identity verification registry on Base.
/// @dev One verified address per passport at any time. The passport nullifier is a
///      privacy-preserving identifier derived via Poseidon hash — it never appears in events.
///      Users can unregister and re-register with a different address after a cooldown period.
interface IVerificationRegistry {
    // =========================================================================
    // Events
    // =========================================================================

    /// @notice Emitted when a wallet successfully registers with a valid ZK proof.
    /// @dev NO nullifier in this event — critical privacy requirement.
    event WalletVerified(address indexed wallet, uint256 timestamp);

    // =========================================================================
    // Write Functions
    // =========================================================================

    /// @notice Register the caller's wallet as identity-verified.
    /// @param zkProof The encoded ZK proof bytes generated by the passport circuit.
    /// @param passportNullifier Privacy-preserving identifier derived from the passport.
    function register(bytes calldata zkProof, bytes32 passportNullifier) external;

    /// @notice Remove the caller's wallet from the verified set.
    /// @param passportNullifier The nullifier used during registration (cached by the app).
    function unregister(bytes32 passportNullifier) external;

    // =========================================================================
    // View Functions
    // =========================================================================

    /// @notice Check if a wallet is currently in the verified set.
    function isVerified(address wallet) external view returns (bool);

    /// @notice Returns the total number of currently-verified wallets.
    function getGroupSize() external view returns (uint256);
}
