// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IVerificationRegistry
/// @notice Interface for the ZK Passport identity verification registry on Base.
/// @dev Wallets call `register()` with a valid ZK proof generated from their passport.
///      The nullifier prevents double-registration with the same passport.
///      The Semaphore identity commitment enables private group membership proofs.
interface IVerificationRegistry {
    // =========================================================================
    // Structs
    // =========================================================================

    /// @notice Tracks usage statistics for a passport nullifier.
    struct NullifierInfo {
        /// @dev How many wallets are currently registered under this nullifier.
        uint256 currentCount;
        /// @dev Block timestamp when currentCount was last increased.
        uint256 currentCountSince;
        /// @dev The highest count ever recorded for this nullifier.
        uint256 peakCount;
        /// @dev Block timestamp when peakCount was achieved.
        uint256 peakCountAchieved;
        /// @dev Block timestamp when peak tracking began.
        uint256 peakCountSince;
    }

    /// @notice Verification data stored per wallet address.
    struct WalletInfo {
        /// @dev Whether this wallet is currently in the verified set.
        bool verified;
        /// @dev True if this wallet was previously registered and then unregistered.
        bool previouslyUnregistered;
        /// @dev How many verified wallets existed when this wallet registered.
        uint256 groupSizeAtVerification;
        /// @dev Block timestamp of the most recent successful registration.
        uint256 verifiedAt;
        /// @dev Semaphore identity commitment submitted during registration.
        uint256 identityCommitment;
    }

    // =========================================================================
    // Events
    // =========================================================================

    /// @notice Emitted when a wallet successfully registers with a valid ZK proof.
    event WalletRegistered(
        address indexed wallet,
        bytes32 indexed nullifier,
        uint256 groupSize,
        uint256 timestamp
    );

    /// @notice Emitted when a wallet unregisters itself.
    event WalletUnregistered(
        address indexed wallet,
        bytes32 indexed nullifier,
        uint256 newGroupSize,
        uint256 timestamp
    );

    // =========================================================================
    // Write Functions
    // =========================================================================

    /// @notice Register the caller's wallet as identity-verified.
    /// @param zkProof The encoded ZK proof bytes generated by zkPassport circuits.
    /// @param nullifier A privacy-preserving identifier derived from the passport.
    /// @param semaphoreIdentityCommitment Poseidon hash of the Semaphore private key.
    function register(
        bytes calldata zkProof,
        bytes32 nullifier,
        uint256 semaphoreIdentityCommitment
    ) external;

    /// @notice Remove the caller's wallet from the verified set.
    function unregister() external;

    // =========================================================================
    // View Functions
    // =========================================================================

    /// @notice Check if a wallet is currently in the verified set.
    function isVerified(address wallet) external view returns (bool);

    /// @notice Get full verification details for a wallet.
    function getWalletInfo(address wallet) external view returns (WalletInfo memory info);

    /// @notice Get usage statistics for a given nullifier.
    function getNullifierInfo(bytes32 nullifier) external view returns (NullifierInfo memory info);
}
