/**
 * VerificationRegistry ABI
 *
 * AUTO-GENERATED by scripts/sync-abi.mjs — do not edit manually.
 * Re-generate with: pnpm contracts:sync-abi
 *
 * Source: packages/contracts/out/VerificationRegistry.sol/VerificationRegistry.json
 */
export const VERIFICATION_REGISTRY_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "governor_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "config_",
        "type": "address",
        "internalType": "contract IProtocolConfig"
      },
      {
        "name": "verifier_",
        "type": "address",
        "internalType": "contract IProofVerifier"
      },
      {
        "name": "cscaMerkleTree_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getBaseExpiry",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPrimaryExpiry",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPrimaryRegisteredAt",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isPrimaryVerified",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isVerified",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerBase",
    "inputs": [
      {
        "name": "epochNullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registerPrimary",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renewBase",
    "inputs": [
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renewPrimary",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "s_config",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IProtocolConfig"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_cscaMerkleTree",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICSCAMerkleTree"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_governor",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_primaryNullifierByWallet",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_primarySlots",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_successor",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "s_verifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IProofVerifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setCSCAMerkleTree",
    "inputs": [
      {
        "name": "newTree",
        "type": "address",
        "internalType": "contract ICSCAMerkleTree"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setConfig",
    "inputs": [
      {
        "name": "newConfig",
        "type": "address",
        "internalType": "contract IProtocolConfig"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSuccessor",
    "inputs": [
      {
        "name": "newSuccessor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setVerifier",
    "inputs": [
      {
        "name": "newVerifier",
        "type": "address",
        "internalType": "contract IProofVerifier"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferGovernance",
    "inputs": [
      {
        "name": "newGovernor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unregisterBase",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unregisterPrimary",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "wasNullifierUsed",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CSCAMerkleTreeUpdated",
    "inputs": [
      {
        "name": "oldTree",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newTree",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigUpdated",
    "inputs": [
      {
        "name": "oldConfig",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newConfig",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceTransferred",
    "inputs": [
      {
        "name": "oldGovernor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newGovernor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SuccessorSet",
    "inputs": [
      {
        "name": "successor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VerifierUpdated",
    "inputs": [
      {
        "name": "oldVerifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newVerifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WalletVerified",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__AlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NotAuthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NotGovernor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NullifierAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__PassportExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__PrimaryInCooldown",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__RateLimitExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__ZeroAddress",
    "inputs": []
  }
] as const;
