/**
 * VerificationRegistry ABI
 *
 * AUTO-GENERATED by scripts/sync-abi.mjs — do not edit manually.
 * Re-generate with: pnpm contracts:sync-abi
 *
 * Source: packages/contracts/out/VerificationRegistry.sol/VerificationRegistry.json
 */
export const VERIFICATION_REGISTRY_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "verifier_",
        "type": "address",
        "internalType": "contract IUltraHonkVerifier"
      },
      {
        "name": "cscaMerkleTree_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "registrationTTL_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxDailyRegistrations_",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getExpiry",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRegisteredAt",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint48",
        "internalType": "uint48"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getWallets",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "i_cscaMerkleTree",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICSCAMerkleTree"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "i_maxDailyRegistrations",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "i_registrationTTL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "i_verifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IUltraHonkVerifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isVerified",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nullifierOf",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "register",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epochNullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renew",
    "inputs": [
      {
        "name": "nullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epochNullifier",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "passportExpiry",
        "type": "uint48",
        "internalType": "uint48"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "s_nullifierByWallet",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unregister",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "WalletVerified",
    "inputs": [
      {
        "name": "wallet",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__AlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__InvalidConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__NullifierMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__PassportExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__RateLimitExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VerificationRegistry__ZeroAddress",
    "inputs": []
  }
] as const;
