// Generated by uniffi-bindgen-react-native
import installer from './NativeMoproFfi';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  try {
    const result = installer.installRustCrate();
    console.log('[MOPRO-INDEX] installRustCrate result:', result);
    console.log('[MOPRO-INDEX] globalThis.NativeZkpassportCircuits:', typeof (globalThis as any).NativeZkpassportCircuits);
  } catch (e) {
    console.error('[MOPRO-INDEX] installRustCrate CRASHED:', e);
  }
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/zkpassport_circuits';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as zkpassport_circuits from './generated/zkpassport_circuits';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  try {
    zkpassport_circuits.default.initialize();
    console.log('[MOPRO-INDEX] initialize succeeded');
  } catch (e) {
    console.error('[MOPRO-INDEX] initialize FAILED:', e);
  }
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  zkpassport_circuits,
};

