#!/usr/bin/env node
/**
 * extract-vk.mjs — Post-processes bb-generated UltraHonk verifiers to extract
 * the verification key into a separate SSTORE2 data contract, keeping the
 * verifier under the 24,576-byte Spurious Dragon size limit.
 *
 * Usage:
 *   node scripts/extract-vk.mjs <generated.sol> <ContractName> <VKContractName> <outDir>
 *
 * Example:
 *   node scripts/extract-vk.mjs target/BaseUltraHonkVerifier.sol BaseUltraHonkVerifier BaseVerificationKey packages/contracts/src/verifiers
 *
 * Outputs:
 *   <outDir>/<ContractName>.sol       — verifier with inline VK removed, EXTCODECOPY loader added
 *   <outDir>/<VKContractName>.sol     — SSTORE2 data contract with VK as deployed bytecode
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const [generatedPath, contractName, vkContractName, outDir] = process.argv.slice(2);

if (!generatedPath || !contractName || !vkContractName || !outDir) {
  console.error('Usage: node extract-vk.mjs <generated.sol> <ContractName> <VKContractName> <outDir>');
  process.exit(1);
}

const src = readFileSync(generatedPath, 'utf8');

// ── 1. Parse the HonkVerificationKey library ──────────────────────────
// Extract the struct initializer block from loadVerificationKey()
const vkMatch = src.match(
  /library\s+HonkVerificationKey\s*\{[\s\S]*?Honk\.VerificationKey\s+memory\s+vk\s*=\s*Honk\.VerificationKey\(\{([\s\S]*?)\}\);[\s\S]*?\}/
);
if (!vkMatch) {
  console.error('Could not find HonkVerificationKey library in generated file');
  process.exit(1);
}

const initBlock = vkMatch[1];

// Parse each field: name: value or name: Honk.G1Point({ x: ..., y: ... })
const fields = {};
const fieldRegex = /(\w+):\s*(?:Honk\.G1Point\(\{\s*x:\s*uint256\((0x[0-9a-fA-F]+)\),\s*y:\s*uint256\((0x[0-9a-fA-F]+)\)\s*\}\)|uint256\((\d+)\))/g;
let m;
while ((m = fieldRegex.exec(initBlock)) !== null) {
  const name = m[1];
  if (m[4] !== undefined) {
    // scalar field
    fields[name] = { type: 'scalar', value: m[4] };
  } else {
    // G1Point
    fields[name] = { type: 'point', x: m[2], y: m[3] };
  }
}

// ── 2. Struct declaration order (MUST match Honk.VerificationKey) ─────
const structOrder = [
  'circuitSize', 'logCircuitSize', 'publicInputsSize',
  'qm', 'qc', 'ql', 'qr', 'qo', 'q4',
  'qLookup', 'qArith', 'qDeltaRange', 'qAux', 'qElliptic',
  'qPoseidon2External', 'qPoseidon2Internal',
  's1', 's2', 's3', 's4',
  'id1', 'id2', 'id3', 'id4',
  't1', 't2', 't3', 't4',
  'lagrangeFirst', 'lagrangeLast',
];

// Validate all fields present
for (const name of structOrder) {
  if (!fields[name]) {
    console.error(`Missing field '${name}' in VK initializer`);
    process.exit(1);
  }
}

// ── 3. Generate assembly mstore lines ─────────────────────────────────
let offset = 0;
const mstoreLines = [];
for (const name of structOrder) {
  const f = fields[name];
  const hex = (n) => '0x' + (n * 0x20).toString(16);
  if (f.type === 'scalar') {
    mstoreLines.push(`            // ${name}`);
    mstoreLines.push(`            mstore(${offset === 0 ? 'm' : `add(m, ${hex(offset)})`}, ${f.value})`);
    offset++;
  } else {
    mstoreLines.push(`            // ${name}`);
    mstoreLines.push(`            mstore(${offset === 0 ? 'm' : `add(m, ${hex(offset)})`}, ${f.x})`);
    offset++;
    mstoreLines.push(`            mstore(add(m, ${hex(offset)}), ${f.y})`);
    offset++;
  }
}

const totalBytes = offset * 32;
const totalHex = '0x' + totalBytes.toString(16);

// ── 4. Write VK data contract ─────────────────────────────────────────
const vkSol = `// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Aztec
pragma solidity >=0.8.21;

/// @title ${vkContractName}
/// @notice SSTORE2-style data contract — deployed bytecode IS the raw VK data.
///         The ${contractName} reads this via EXTCODECOPY into a Honk.VerificationKey struct.
///
/// @dev Auto-generated by scripts/extract-vk.mjs — do not edit manually.
///      Data layout: ${offset} consecutive uint256 words (${totalBytes} bytes) matching the
///      Honk.VerificationKey struct memory layout.
contract ${vkContractName} {
    constructor() {
        assembly {
            let m := mload(0x40)

${mstoreLines.join('\n')}

            // ${offset} words × 32 bytes = ${totalBytes} = ${totalHex}
            return(m, ${totalHex})
        }
    }
}
`;

writeFileSync(join(outDir, `${vkContractName}.sol`), vkSol);
console.log(`  ✅ ${vkContractName}.sol written`);

// ── 5. Patch the verifier contract ────────────────────────────────────
// Extract the constants (N, LOG_N, NUMBER_OF_PUBLIC_INPUTS) from before the library
const constantsMatch = src.match(
  /(\/\/[^\n]*\n)*pragma solidity[^\n]+\n\n(uint256 constant N[^\n]+\nuint256 constant LOG_N[^\n]+\nuint256 constant NUMBER_OF_PUBLIC_INPUTS[^\n]+\n)/
);
if (!constantsMatch) {
  console.error('Could not find top-level constants in generated file');
  process.exit(1);
}

// Remove everything from "library HonkVerificationKey" to its closing "}"
// The library ends before the next "pragma solidity" or "type Fr" declaration
let patched = src.replace(
  /library\s+HonkVerificationKey\s*\{[\s\S]*?\n\}\n/,
  `// VK data is stored externally in ${vkContractName}.sol (SSTORE2 pattern)\n// to keep this contract under the 24,576-byte Spurious Dragon size limit.\n`
);

// Replace the contract's loadVerificationKey function
patched = patched.replace(
  /contract\s+(\w+)\s+is\s+IVerifier\s*\{[\s\S]*?function\s+loadVerificationKey\(\)\s+internal\s+pure\s+returns\s*\(Honk\.VerificationKey\s+memory\s+vk\)\s*\{[^}]+\}/,
  `contract ${contractName} is IVerifier {
    using FrLib for Fr;

    /// @notice Address of the SSTORE2 data contract containing the ABI-encoded VK.
    address public immutable vkDataContract;

    constructor(address _vkDataContract) {
        vkDataContract = _vkDataContract;
    }

    /// @dev Loads verification key from external data contract via EXTCODECOPY.
    ///      The data contract's bytecode is the raw VK struct data — a direct copy works
    ///      because the struct contains only fixed-size types (uint256 and G1Point).
    function loadVerificationKey() internal view returns (Honk.VerificationKey memory vk) {
        address _vkAddr = vkDataContract;
        assembly {
            extcodecopy(_vkAddr, vk, 0, extcodesize(_vkAddr))
        }
    }`
);

writeFileSync(join(outDir, `${contractName}.sol`), patched);
console.log(`  ✅ ${contractName}.sol written (VK extracted)`);
