#!/usr/bin/env node
/**
 * sync-abi.mjs — ABI Sync Agent
 *
 * Reads the compiled VerificationRegistry ABI from Foundry's output,
 * then generates apps/mobile/src/infrastructure/blockchain/contractAbis.ts
 * so the mobile app always has an up-to-date ABI.
 *
 * Usage:
 *   node scripts/sync-abi.mjs
 *   pnpm contracts:sync-abi
 *
 * Run after any change to VerificationRegistry.sol (after forge build).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const FOUNDRY_OUTPUT = resolve(
  ROOT,
  'packages/contracts/out/VerificationRegistry.sol/VerificationRegistry.json',
);
const TARGET = resolve(
  ROOT,
  'apps/mobile/src/infrastructure/blockchain/contractAbis.ts',
);

// Read and parse the Foundry artifact
let artifact;
try {
  artifact = JSON.parse(readFileSync(FOUNDRY_OUTPUT, 'utf8'));
} catch (err) {
  console.error(
    `[sync-abi] Could not read Foundry artifact at:\n  ${FOUNDRY_OUTPUT}\n\nRun "pnpm contracts:build" first.\n`,
  );
  process.exit(1);
}

const abi = artifact.abi;
if (!Array.isArray(abi)) {
  console.error('[sync-abi] Artifact does not contain a valid .abi array.');
  process.exit(1);
}

const abiJson = JSON.stringify(abi, null, 2);

const output = `/**
 * VerificationRegistry ABI
 *
 * AUTO-GENERATED by scripts/sync-abi.mjs — do not edit manually.
 * Re-generate with: pnpm contracts:sync-abi
 *
 * Source: packages/contracts/out/VerificationRegistry.sol/VerificationRegistry.json
 */
export const VERIFICATION_REGISTRY_ABI = ${abiJson} as const;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`[sync-abi] ABI synced (${abi.length} entries) → ${TARGET}`);
