// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Aztec
pragma solidity >=0.8.21;

/// @title BaseVerificationKey
/// @notice SSTORE2-style data contract — deployed bytecode IS the raw VK data.
///         The UltraHonk verifier reads this via EXTCODECOPY into a Honk.VerificationKey struct.
///
/// @dev Auto-generated by scripts/mopro-vk-to-solidity.mjs from Mopro's in-memory VK
///      (zkmopro bb fork format). Do not edit manually.
///      Data layout: 59 consecutive uint256 words (1888 bytes) matching the
///      Honk.VerificationKey struct memory layout.
contract BaseVerificationKey {
    constructor() {
        assembly {
            let m := mload(0x40)

            // circuitSize
            mstore(m, 524288)
            // logCircuitSize
            mstore(add(m, 0x20), 19)
            // publicInputsSize
            mstore(add(m, 0x40), 19)
            // qm
            mstore(add(m, 0x60), 0x1d0805a7b7c041abc1804890224972eae58f7e6b7c98d139873cc50e78dda3f4)
            mstore(add(m, 0x80), 0x0c300adc2f465e697947206568ee4bf848d8f45cc641483ab396191765070f07)
            // qc
            mstore(add(m, 0xa0), 0x1c47d6c8890ef627997a023ef91c0b0b1abff2fa9f40d12ce0a88de3a85a09b6)
            mstore(add(m, 0xc0), 0x0caec52659a63945d46f2a8255421f2d0bcc8baee0d00119d8a492470ea49b5c)
            // ql
            mstore(add(m, 0xe0), 0x109c03afd2be073e83f5ee2184b28a040c6ac31ebd027cb251310169fe11b196)
            mstore(add(m, 0x100), 0x2e8ce11ffa07021a2e7d6dc841fc8248a04471323bc5fa1467dbb25fdeb690ba)
            // qr
            mstore(add(m, 0x120), 0x256f1006f463d20458cdb6681bcebb332fcf24482915d0d6e504f6a305d71e6f)
            mstore(add(m, 0x140), 0x025f4a6ec8b62636947bf41ee399cbe7fdd1ff304259747bc311453eada729a5)
            // qo
            mstore(add(m, 0x160), 0x2ff7ee59373737b0a01129f58f3f323dc153531f5448d0ff64adc01e8822d5c2)
            mstore(add(m, 0x180), 0x080e569b99091c0b3e452a671e3846c8fda35a5d9c8174b849104ead490df5f4)
            // q4
            mstore(add(m, 0x1a0), 0x1a6d921e6762389fc14a6de7c8080af93a37d5b652f666377c817bcc5045e8b0)
            mstore(add(m, 0x1c0), 0x22baa5153d09b73ac4d088ca5563e722bf5a2b724198568ed5ba027ca4ca0612)
            // qLookup
            mstore(add(m, 0x1e0), 0x2f7f3c752364fcd3fb99e42aeb0f02af8f3fa5b7774e9759e5c79ba3f23dd2dc)
            mstore(add(m, 0x200), 0x17b487fd29be453710e72aa796756d84a166e429274dc2a878011c80481436f9)
            // qArith
            mstore(add(m, 0x220), 0x277f36ae4fc203d257decd4c715ea74de8ec413cc1a7c7c07cf8d28f044ebcab)
            mstore(add(m, 0x240), 0x2bbc8dc9ea281ab95b36dec04287a68cf286ede30edab92cc696fbef2b688aad)
            // qDeltaRange
            mstore(add(m, 0x260), 0x0452df34ba23ce21358837e2f46c33d8c7aa7eeba788e3ea10ed26ba311010e7)
            mstore(add(m, 0x280), 0x0f8cb8bb7f69257a921b4f06de2b432cf80e2ca887ff7ad020a7dae19f543d3e)
            // qMemory
            mstore(add(m, 0x2a0), 0x2d98c4e734736a29dff8db75c05c31b6d1694a4b13f1a6f62b1070612ac5d00b)
            mstore(add(m, 0x2c0), 0x0e23ab70a31b244398a1bf7daeb3509ace24fcbab890b7574b6b9172a6d05265)
            // qNnf
            mstore(add(m, 0x2e0), 0x1c28f0510fe5be9f15e3a2d303e29ff19f3adf7820119a3fb9a554c448157fc8)
            mstore(add(m, 0x300), 0x223f1bb9c113398b6b572bf2dcec739f4a179024dcc29fb486572d76e825c72a)
            // qElliptic
            mstore(add(m, 0x320), 0x2072d3f601624b23b1fe024c17a1dacb954d56ac8a3c80d10fdb76d13a44a058)
            mstore(add(m, 0x340), 0x1ab841468ba906528bd1b165655525298edde6da6d15e19b1bdf4179d8e9b535)
            // qPoseidon2External
            mstore(add(m, 0x360), 0x27925b3b11f0c33023db11477aa22f5ae003de1c5d1cf082ddf78f2dceb25d59)
            mstore(add(m, 0x380), 0x2c11922cb264a0aaa4ce7dfd086df0a39f33e1a63776cd832a9465c8af936549)
            // qPoseidon2Internal
            mstore(add(m, 0x3a0), 0x0bdaef35f020f053896f855310ed89c9507065e25afa7b49d8edd29d7c30b8b8)
            mstore(add(m, 0x3c0), 0x302415f5b0d3385dd6537fd5b9ee4764f17847fde0d8b3f3f8c0bb4b7e5dca40)
            // s1
            mstore(add(m, 0x3e0), 0x2f65f3832a736bcc123d5b0d60d7a70bac5e54cedfdb03a4259d95931574ee45)
            mstore(add(m, 0x400), 0x0aabd79a45e1d9b76195b3d01c81a7db45438b5fe85e9d56693c660c48842d14)
            // s2
            mstore(add(m, 0x420), 0x1327ed33fe623b941960a69c3fa8f83a1291110204b54f8b24e23f5f49a45af1)
            mstore(add(m, 0x440), 0x2c92a215f6a72edb0c34a708f7b3279b893c4705c6b47fd29f1a5f7aeed45e51)
            // s3
            mstore(add(m, 0x460), 0x049824edf3ff2dd0fd3d0abb65614dda6696a07324548e63a9402ae03500352b)
            mstore(add(m, 0x480), 0x21f8291b6a66cc88f440712c7bf08b096256cf34bbee610d405256e528ceee2e)
            // s4
            mstore(add(m, 0x4a0), 0x1e08f4b63c55d2ca17044c127c11f42355bb929147c0024c59f4076e524d073e)
            mstore(add(m, 0x4c0), 0x255a9cf66e3dcbd2a824fbc196c08ba287215158681f013efcdafce7d85d3228)
            // id1
            mstore(add(m, 0x4e0), 0x02adb66b7529264e5f0cf3a3436d42bca5a7ea38a839fdbc5144bc21d5f29e1a)
            mstore(add(m, 0x500), 0x1bfb6d82788e9eaa15ba60e9fbc88c49dfac611c5f66a3ad20ff4e6cbd113549)
            // id2
            mstore(add(m, 0x520), 0x16a281800039e821f1e0b65f38bb3cc29159abf60f2cbb068f7670537690c1fe)
            mstore(add(m, 0x540), 0x2365ffbab175fa1721dda8ac60dc1522029ccbc6b86970be9c966a0912eb78fd)
            // id3
            mstore(add(m, 0x560), 0x1212cf03ba92c3492a1996203b6e60b7316ad5a3d0426ae3330def352d2cce3d)
            mstore(add(m, 0x580), 0x0297776f313d361f6ae5c98f15688966f19b2c7f25276aa031f9fa8e513386be)
            // id4
            mstore(add(m, 0x5a0), 0x1228c6d366a6f3ea01c9dfc8d64fb0563ce6bba4222f039eb5f97c57e879920b)
            mstore(add(m, 0x5c0), 0x29d026d67ec7e1211d8c213ff0cb6654c81b880999f5e3f82555e25e21d70fa4)
            // t1
            mstore(add(m, 0x5e0), 0x0721ab622e3899d1164f3cf8c1bf06725ce8e8fb5c6346f6dfeb9261eb398cee)
            mstore(add(m, 0x600), 0x08c3893f3d828ecea492501dbd4a5c9656984ef9db170ea5f30f9ec4165d1919)
            // t2
            mstore(add(m, 0x620), 0x036cb36e7e154ac681f44700b5ebfbb4ea037a98206a837386972f51514e7707)
            mstore(add(m, 0x640), 0x120960ff3c95454dc197ec3038c0b7fb4c91717eaa15464ec1ce1a66cc2bc84d)
            // t3
            mstore(add(m, 0x660), 0x10c66b56fffb78992b9e917ea46680ecd75a43477d5420ab712cb3770dddaa8a)
            mstore(add(m, 0x680), 0x2673e83943cdd143a76a88328d3127cbcf4236a4b9a28eef9f38438f6809c75c)
            // t4
            mstore(add(m, 0x6a0), 0x0f3ffd48df2972678acc44800f54cede6c251949ab9720c5726addf449f582b8)
            mstore(add(m, 0x6c0), 0x08c95ecb36077b4e651f295f120335891b2672889eeb03795f85ee676a1b6792)
            // lagrangeFirst
            mstore(add(m, 0x6e0), 0x0000000000000000000000000000000000000000000000000000000000000001)
            mstore(add(m, 0x700), 0x0000000000000000000000000000000000000000000000000000000000000002)
            // lagrangeLast
            mstore(add(m, 0x720), 0x1b80746da61a59929e69cdf8d122fdc22bc7bd2994bc61f048dbb465b5ccb218)
            mstore(add(m, 0x740), 0x00dd4dea7f7ab958de371c4d03a873a978bbb1fa4f02945798357e978bf4180d)

            // 59 words × 32 bytes = 1888 = 0x760
            return(m, 0x760)
        }
    }
}
