// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Aztec
pragma solidity >=0.8.21;

/// @title BaseVerificationKey
/// @notice SSTORE2-style data contract — deployed bytecode IS the raw VK data.
///         The BaseUltraHonkVerifier reads this via EXTCODECOPY into a Honk.VerificationKey struct.
///
/// @dev Auto-generated by scripts/extract-vk.mjs — do not edit manually.
///      Data layout: 59 consecutive uint256 words (1888 bytes) matching the
///      Honk.VerificationKey struct memory layout.
contract BaseVerificationKey {
    constructor() {
        assembly {
            let m := mload(0x40)

            // circuitSize
            mstore(m, 524288)
            // logCircuitSize
            mstore(add(m, 0x20), 19)
            // publicInputsSize
            mstore(add(m, 0x40), 19)
            // qm
            mstore(add(m, 0x60), 0x25f41f0687149072b78bfeca4d52446c81e3b8b0563e966fafac2a9beb83a16f)
            mstore(add(m, 0x80), 0x04c8d8b588d66b57b2d32cdb4b686da34096696e26d67f8eb89223b49525f696)
            // qc
            mstore(add(m, 0xa0), 0x1c47d6c8890ef627997a023ef91c0b0b1abff2fa9f40d12ce0a88de3a85a09b6)
            mstore(add(m, 0xc0), 0x0caec52659a63945d46f2a8255421f2d0bcc8baee0d00119d8a492470ea49b5c)
            // ql
            mstore(add(m, 0xe0), 0x013e2fb5907a2899f10184834198edd6b68358e47e4c5400a218e387060cd627)
            mstore(add(m, 0x100), 0x0a95ff80dd4800ff344759c490c8f419a6ee4782ca92dc6dfc925c466ba39706)
            // qr
            mstore(add(m, 0x120), 0x203bc4f0a426a412e07b6352c1c201ef3943c1fb92123f16690ca3722e5cfd68)
            mstore(add(m, 0x140), 0x12140b6396c3d4ed4e860c3c70816b09bf2145a67ecdae1138c166d7de893a1a)
            // qo
            mstore(add(m, 0x160), 0x019fa6042838d862707344a9453a2e06015fa8806d3dcfffacfe63bb36e5bfd9)
            mstore(add(m, 0x180), 0x15ebe1e47b2757a820ecca3552927c9142db65ad04e0b47bb0b4e15cdb886f41)
            // q4
            mstore(add(m, 0x1a0), 0x1c268efa40dfe4f8af5b7aa9a5c8308d5b87b41b7744b3fcc549e8823d146375)
            mstore(add(m, 0x1c0), 0x08a8c51dce149d9870334ec3895003727c989c2de20e3cc763df2939b56ed710)
            // qLookup
            mstore(add(m, 0x1e0), 0x2f7f3c752364fcd3fb99e42aeb0f02af8f3fa5b7774e9759e5c79ba3f23dd2dc)
            mstore(add(m, 0x200), 0x17b487fd29be453710e72aa796756d84a166e429274dc2a878011c80481436f9)
            // qArith
            mstore(add(m, 0x220), 0x1624b0b68d77515aea66e8dd7db1e03cbc78e6dcd447475c5b3a74c98fae7f59)
            mstore(add(m, 0x240), 0x16090b9956df28f4b118540ac405336f51e6c0d94dfe6090c05f7608ec7b03a1)
            // qDeltaRange
            mstore(add(m, 0x260), 0x0452df34ba23ce21358837e2f46c33d8c7aa7eeba788e3ea10ed26ba311010e7)
            mstore(add(m, 0x280), 0x0f8cb8bb7f69257a921b4f06de2b432cf80e2ca887ff7ad020a7dae19f543d3e)
            // qMemory
            mstore(add(m, 0x2a0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            mstore(add(m, 0x2c0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            // qNnf
            mstore(add(m, 0x2e0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            mstore(add(m, 0x300), 0x0000000000000000000000000000000000000000000000000000000000000000)
            // qElliptic
            mstore(add(m, 0x320), 0x2072d3f601624b23b1fe024c17a1dacb954d56ac8a3c80d10fdb76d13a44a058)
            mstore(add(m, 0x340), 0x1ab841468ba906528bd1b165655525298edde6da6d15e19b1bdf4179d8e9b535)
            // qPoseidon2External
            mstore(add(m, 0x360), 0x0c92609b3e9ce9742c03c438d41aa69d6f59e9cf47e25dc5ab4756946e10dae0)
            mstore(add(m, 0x380), 0x2faf026b1399698985dacafaf6b45038f0e9be7739f263a6c2fa959e30c4c01f)
            // qPoseidon2Internal
            mstore(add(m, 0x3a0), 0x144ec01aa300cea4d21e6dcdebf743610892e25ef0efb77f30e3737a98c0472a)
            mstore(add(m, 0x3c0), 0x1109f8ddeb031366cff71932b3b17a1ba7729767b4c734640bc5755a1f545472)
            // s1
            mstore(add(m, 0x3e0), 0x2acc3de8bcca0b4c69d03712d468a3592336fa47372d29adb9808bc1c80400d4)
            mstore(add(m, 0x400), 0x2da9729d7ef7907b7df7f0266f53db1bede064faa0dae9431ce8e519045d43f8)
            // s2
            mstore(add(m, 0x420), 0x0dc1218db20cbbe6347d02f127c00728395139c16403fea946c077dc4fd44bab)
            mstore(add(m, 0x440), 0x0aee94270fc45dcf2a729e216bad86cbcb0d988bc3cc0b477daf5f0fbb05826b)
            // s3
            mstore(add(m, 0x460), 0x05a3234c55aeee80ed03e78d41b736e64d17e3e90e38f322bb9a9dbeb0941bb2)
            mstore(add(m, 0x480), 0x2d02cf633448de5276e7a40598598f7d7605483d2d7782421245ea22db5ac1c0)
            // s4
            mstore(add(m, 0x4a0), 0x2a3f0f495c3b734b21c574a158acad604850239f5075726848eb00a2349914a9)
            mstore(add(m, 0x4c0), 0x07b988b8bf529b9d41b7f80bb97a31ec60a56281cc0614ae9985809bb2d34030)
            // id1
            mstore(add(m, 0x4e0), 0x1e434bd0adba60635e649daf6cac4366a822eb0cd47747995de5853206fa3026)
            mstore(add(m, 0x500), 0x0fa7f4937e5b22bdb77a3f3b1c60bf5ab5b54922225e2aee625e5619f3090da6)
            // id2
            mstore(add(m, 0x520), 0x2168ebd6470ca320052aa10b24c441fc71fb0dc4931c754d1b2105a40c935ceb)
            mstore(add(m, 0x540), 0x239933aa9e7b47abfa56aba3384231739e3bcc6e9c176b80bc7611c1d7be2cef)
            // id3
            mstore(add(m, 0x560), 0x155a6af533ab258aefc3f61f1592b020f438100ddc5f5a34c02577223bafc539)
            mstore(add(m, 0x580), 0x22a63c668aa1baece99e22ca6031f0ab5f07a565cab6e804dc44cf52275e72a2)
            // id4
            mstore(add(m, 0x5a0), 0x2278978ef8a707fd4fe1689f8959769ddc156bfb583b2e96f6fa1a8b33a90a73)
            mstore(add(m, 0x5c0), 0x1d71115fd746b68efcebec7610c928913777634bdd462e6914663221385fa77a)
            // t1
            mstore(add(m, 0x5e0), 0x0721ab622e3899d1164f3cf8c1bf06725ce8e8fb5c6346f6dfeb9261eb398cee)
            mstore(add(m, 0x600), 0x08c3893f3d828ecea492501dbd4a5c9656984ef9db170ea5f30f9ec4165d1919)
            // t2
            mstore(add(m, 0x620), 0x036cb36e7e154ac681f44700b5ebfbb4ea037a98206a837386972f51514e7707)
            mstore(add(m, 0x640), 0x120960ff3c95454dc197ec3038c0b7fb4c91717eaa15464ec1ce1a66cc2bc84d)
            // t3
            mstore(add(m, 0x660), 0x10c66b56fffb78992b9e917ea46680ecd75a43477d5420ab712cb3770dddaa8a)
            mstore(add(m, 0x680), 0x2673e83943cdd143a76a88328d3127cbcf4236a4b9a28eef9f38438f6809c75c)
            // t4
            mstore(add(m, 0x6a0), 0x0f3ffd48df2972678acc44800f54cede6c251949ab9720c5726addf449f582b8)
            mstore(add(m, 0x6c0), 0x08c95ecb36077b4e651f295f120335891b2672889eeb03795f85ee676a1b6792)
            // lagrangeFirst
            mstore(add(m, 0x6e0), 0x0000000000000000000000000000000000000000000000000000000000000001)
            mstore(add(m, 0x700), 0x0000000000000000000000000000000000000000000000000000000000000002)
            // lagrangeLast
            mstore(add(m, 0x720), 0x15689a0157207826bbabae40eade8bb9f4c0370ae158a67265ecdee694a53957)
            mstore(add(m, 0x740), 0x0441aec15d10d4488315d74d9706829a09d2cc947d6f2c188dd686e40336b99a)

            // 59 words × 32 bytes = 1888 = 0x760
            return(m, 0x760)
        }
    }
}
