// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Aztec
pragma solidity >=0.8.21;

/// @title PrimaryVerificationKey
/// @notice SSTORE2-style data contract — deployed bytecode IS the raw VK data.
///         The UltraHonk verifier reads this via EXTCODECOPY into a Honk.VerificationKey struct.
///
/// @dev Auto-generated by scripts/mopro-vk-to-solidity.mjs from Mopro's in-memory VK
///      (zkmopro bb fork format). Do not edit manually.
///      Data layout: 59 consecutive uint256 words (1888 bytes) matching the
///      Honk.VerificationKey struct memory layout.
contract PrimaryVerificationKey {
    constructor() {
        assembly {
            let m := mload(0x40)

            // circuitSize
            mstore(m, 524288)
            // logCircuitSize
            mstore(add(m, 0x20), 19)
            // publicInputsSize
            mstore(add(m, 0x40), 20)
            // qm
            mstore(add(m, 0x60), 0x283f87f056b89b59509d6722ebb9737736bb0d56229f803b42d8c4f14d1a7fde)
            mstore(add(m, 0x80), 0x076aa21aa8e4dcfd23770c8ceb353d0393b0c8175dbc0c49f7b9656ba525e57d)
            // qc
            mstore(add(m, 0xa0), 0x2d6e6ad603fc1ab8c634d4036311d85d528d7d6ecc27db28263ac36148937136)
            mstore(add(m, 0xc0), 0x0c5b4bbd67f8898780eec232eaa4fcebf214c5bd40427f9b393187bbf229c83f)
            // ql
            mstore(add(m, 0xe0), 0x202d673f9261560fca1e9f33ce2df3d6b64085e0296b484016a493134d0b121d)
            mstore(add(m, 0x100), 0x022392312dec875de6bf416b04314b4fd2b8d7ff8a00bd8f69805f626175aa49)
            // qr
            mstore(add(m, 0x120), 0x1473b596ddd0c8b87feb072912e66cd08e7c6a473f8b011977876d8ef44234b1)
            mstore(add(m, 0x140), 0x2890be640448ffc878574f7173b3abbaf1723417ebae7edf98b3cb51d55672ae)
            // qo
            mstore(add(m, 0x160), 0x07a63484173c4fb76c88f7d316a599b32fb8ace20debcbcfe17c7c417dad2d31)
            mstore(add(m, 0x180), 0x278322e72e8767ca5326a8b2406dbf567ff42b01ee9eaeeaa849c0b42dad7038)
            // q4
            mstore(add(m, 0x1a0), 0x1355107a7a0916c77853b11133668d003d9db98471c65f5515b3876ebedb6916)
            mstore(add(m, 0x1c0), 0x22604b4d4b23ad5cb1847f325db5e0fa5d184cc968a8b68912a31c8ba98fc179)
            // qLookup
            mstore(add(m, 0x1e0), 0x182501883120724e0539f92d272ff55f10e4f38ba085479b3e8309a53e1d2f3b)
            mstore(add(m, 0x200), 0x18f1952374932674462219f5c989b691ca8752061c73a2293a25cb1b8fb5e13f)
            // qArith
            mstore(add(m, 0x220), 0x07cb8ff5253e9f87135ab22fdda928d7f2f6d1f4787fdec918fd44927620caad)
            mstore(add(m, 0x240), 0x05b9487910016ba198bdcd476eeb2fa70abbf8130b06600afdf5d10db3308640)
            // qDeltaRange
            mstore(add(m, 0x260), 0x2cee4b36fab9c7ad1fdfd9d10ce91b777cbac449f1f0c093baf6ccb05244cabf)
            mstore(add(m, 0x280), 0x08b852666663e8dc78daebf4ac3053f26b443af7f0736166bf948306579cef5a)
            // qMemory
            mstore(add(m, 0x2a0), 0x0ef8bfada1596aa322529fe723e092c6519004248658d103cd62b80c5ebb92ec)
            mstore(add(m, 0x2c0), 0x21caa5f5690f15b0af19569516c984b4444d4b450d4beb41b34df4d29a8d32fd)
            // qNnf
            mstore(add(m, 0x2e0), 0x0437a5e21885feb44462d22d54a78778beeb1b336a673aa5beffca618143916f)
            mstore(add(m, 0x300), 0x25db0b0ebd88209342f4af318ba3082ca7e23d449c1817096ae9f969bef39847)
            // qElliptic
            mstore(add(m, 0x320), 0x04d17920b65cd228578483168f810e4598e457904c4ce03a23f9bc335aa25e40)
            mstore(add(m, 0x340), 0x186f5d7077fd67d5a08c6125d04879d62e4794671d48c8c2ed804e95621459ea)
            // qPoseidon2External
            mstore(add(m, 0x360), 0x031baa92ec8cac5b28493594c9073f0f46e9fbf86c194a4106d519c01886458b)
            mstore(add(m, 0x380), 0x284f00aa37cb2662beae2040eb8bf4ad6033f3a0f7236ce9be462bd67fe3e108)
            // qPoseidon2Internal
            mstore(add(m, 0x3a0), 0x251c541c8318e05986a46e5cae4f93a15099b26310d492a26dce3818059608f6)
            mstore(add(m, 0x3c0), 0x138996772400ca80017fba3c37b3cad55c7d1846498d7339bac6853f000003bc)
            // s1
            mstore(add(m, 0x3e0), 0x25ac6f6c066bf4a5df4ecde9fc71f3d22d515e4b90a5314907574d8d18c160bb)
            mstore(add(m, 0x400), 0x1f6a22dadb9940940a3a41ce22b784f06a7b18f1cd4174ca5b8a79f5babe2e35)
            // s2
            mstore(add(m, 0x420), 0x2fa6158ad39ee6528c3f0a541bbfc32159964617ded9504304111cf7ceb21314)
            mstore(add(m, 0x440), 0x046745b183fa6c18cf9c88471302a7f4ddfde7309d9887350a335b37b97b9aeb)
            // s3
            mstore(add(m, 0x460), 0x1567a1051b89f1e679e80dfc8faefa1255889479556d653f3e62eade7568b6d9)
            mstore(add(m, 0x480), 0x2c0336bbb8cd89643ca4c34d975343c773e97b16c61dc226f650b5e7c9e3b4a3)
            // s4
            mstore(add(m, 0x4a0), 0x2e3e3fce041650aa225a53b394bcab91f2618474d75960717d86db65413d421d)
            mstore(add(m, 0x4c0), 0x0ab93ed96dfe84038b43b3d864b9542ea08c9e50b0e09a759426a408ecfb8ca6)
            // id1
            mstore(add(m, 0x4e0), 0x1ce899ba56527d91867965648be3a8ba86b377e10b10ca44aef27d9717edf32e)
            mstore(add(m, 0x500), 0x0eeb7045bbe102dfb6787c5f2129dd61b2135b4c20c5f98d9693a68d6cad6ca8)
            // id2
            mstore(add(m, 0x520), 0x222d46946538c409ffea41eb627277c720ed76319a8593135266fb89c0a22b8e)
            mstore(add(m, 0x540), 0x249a1559f2db30d0a282b8e53338242a2f24e82e169d6b1fe49a1184ea037ecb)
            // id3
            mstore(add(m, 0x560), 0x296f961bb1d6f69a49930d06b1cda7d430e9fc3269cb47ab7813529218f86364)
            mstore(add(m, 0x580), 0x16cb3b2006422c94abbf12813855eebf0bbbfb58aae63c35617607d1cc6359ee)
            // id4
            mstore(add(m, 0x5a0), 0x25bff5d56fe8fbac38ffc647f8731e9564c3fec31c3e127cf5a341dffd47cb33)
            mstore(add(m, 0x5c0), 0x0851181800e7774c9e6e3b608aa7aebbf3a7d2fad483b4498ee4a5b5e1d3d756)
            // t1
            mstore(add(m, 0x5e0), 0x0117ed333c8f7b65c9d52f5c2371c5c75fe69d4bf722eb517be7382eaffcb205)
            mstore(add(m, 0x600), 0x1a47a010417bdf8c0825bed565bd29e325ac8e6301427ffcbaf9e1790e8a29b7)
            // t2
            mstore(add(m, 0x620), 0x1c9c07dc8213c42d0f00c967b510e43d22c9a15e1413a27b0cf1f6e38264992b)
            mstore(add(m, 0x640), 0x0034d4b14d1cf84231ce71b6b4e558aab36e98fcde16ce45927a1ce2b30c7993)
            // t3
            mstore(add(m, 0x660), 0x25543785070c19ef752a9699d2d64b6677fc2f42648e30f171d5099f0819e9e0)
            mstore(add(m, 0x680), 0x2266b79c3483b16aace77a21be7ae9db092476aca4336f7b8fa8244017afa3fa)
            // t4
            mstore(add(m, 0x6a0), 0x1ebd743b2bb94ad54c579e0a45e199d98e660b1a7cd3468bb20305a9bf15c44f)
            mstore(add(m, 0x6c0), 0x1142f8a773d36ab7b120f4547469e93c71a76608e1a3540496e9ee4bf2dd67a3)
            // lagrangeFirst
            mstore(add(m, 0x6e0), 0x0000000000000000000000000000000000000000000000000000000000000001)
            mstore(add(m, 0x700), 0x0000000000000000000000000000000000000000000000000000000000000002)
            // lagrangeLast
            mstore(add(m, 0x720), 0x1224fbd96f01eb4f005113eb560551c5ca7db311981ce861629b5a80242d8585)
            mstore(add(m, 0x740), 0x0a7429414b4edd44ef0b5f48a6705e79d16bf611634caabe4332d2c47a8731ed)

            // 59 words × 32 bytes = 1888 = 0x760
            return(m, 0x760)
        }
    }
}
