// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Aztec
pragma solidity >=0.8.21;

/// @title PrimaryVerificationKey
/// @notice SSTORE2-style data contract — deployed bytecode IS the raw VK data.
///         The PrimaryUltraHonkVerifier reads this via EXTCODECOPY into a Honk.VerificationKey struct.
///
/// @dev Auto-generated by scripts/extract-vk.mjs — do not edit manually.
///      Data layout: 59 consecutive uint256 words (1888 bytes) matching the
///      Honk.VerificationKey struct memory layout.
contract PrimaryVerificationKey {
    constructor() {
        assembly {
            let m := mload(0x40)

            // circuitSize
            mstore(m, 524288)
            // logCircuitSize
            mstore(add(m, 0x20), 19)
            // publicInputsSize
            mstore(add(m, 0x40), 20)
            // qm
            mstore(add(m, 0x60), 0x2a16efd94d13e00ba4389b12971574aa10ebe89069fd55419325d00113b6240b)
            mstore(add(m, 0x80), 0x212ca1cc71c227cec5596927ca90e37a32787176e4b491ce35ca715f516bfc19)
            // qc
            mstore(add(m, 0xa0), 0x2d6e6ad603fc1ab8c634d4036311d85d528d7d6ecc27db28263ac36148937136)
            mstore(add(m, 0xc0), 0x0c5b4bbd67f8898780eec232eaa4fcebf214c5bd40427f9b393187bbf229c83f)
            // ql
            mstore(add(m, 0xe0), 0x0b8d3adf2c5aa7c3b0730492735b3011fb00eb9d852cf7843d950fdaf77e664d)
            mstore(add(m, 0x100), 0x2d387354e1cf637573ec423797dda750e909be5b211a210474d062a9d37789c7)
            // qr
            mstore(add(m, 0x120), 0x07f61661d8d183a414f231e94575824a8213a90333930c2fc7fcb8c7194f64b9)
            mstore(add(m, 0x140), 0x10f4d00beae890b5b08f8a449764599fcf1be330059cfea6271b49105f34d454)
            // qo
            mstore(add(m, 0x160), 0x2da77379b0770d92d8f69f9c6b76ef903331b696a2fc057dd8617b5b4fa37309)
            mstore(add(m, 0x180), 0x11be1641a1ab858715c85383ae4eb3fc24e6d5c3490ac5b9e3d0220adf590d52)
            // q4
            mstore(add(m, 0x1a0), 0x1b1d45b6f1d18280d56fc06d13b860e2af37c83b9b145df9f6113eb6355cf6b7)
            mstore(add(m, 0x1c0), 0x07cd12cb3b9119e136d151e1ace8fb1baea59104a14195e2dc1fbfd698fe3f35)
            // qLookup
            mstore(add(m, 0x1e0), 0x182501883120724e0539f92d272ff55f10e4f38ba085479b3e8309a53e1d2f3b)
            mstore(add(m, 0x200), 0x18f1952374932674462219f5c989b691ca8752061c73a2293a25cb1b8fb5e13f)
            // qArith
            mstore(add(m, 0x220), 0x01b3d8b2590b8e6c31e537ca6ea0d46b041e5f8164696dcfe395196b5056842d)
            mstore(add(m, 0x240), 0x2327144fef737cd7476d431a0cf010ae3dc29c7d98f256721c0fca30bea4deb9)
            // qDeltaRange
            mstore(add(m, 0x260), 0x2cee4b36fab9c7ad1fdfd9d10ce91b777cbac449f1f0c093baf6ccb05244cabf)
            mstore(add(m, 0x280), 0x08b852666663e8dc78daebf4ac3053f26b443af7f0736166bf948306579cef5a)
            // qMemory
            mstore(add(m, 0x2a0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            mstore(add(m, 0x2c0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            // qNnf
            mstore(add(m, 0x2e0), 0x0000000000000000000000000000000000000000000000000000000000000000)
            mstore(add(m, 0x300), 0x0000000000000000000000000000000000000000000000000000000000000000)
            // qElliptic
            mstore(add(m, 0x320), 0x04d17920b65cd228578483168f810e4598e457904c4ce03a23f9bc335aa25e40)
            mstore(add(m, 0x340), 0x186f5d7077fd67d5a08c6125d04879d62e4794671d48c8c2ed804e95621459ea)
            // qPoseidon2External
            mstore(add(m, 0x360), 0x1cfa633e435db26f55f91dc9cf80f0c25602f89cce3962b7d3dd74091a19caa9)
            mstore(add(m, 0x380), 0x24aa8f52da7257b290c9659a38b31f3bc1f796300857d9e1daacb128378130d9)
            // qPoseidon2Internal
            mstore(add(m, 0x3a0), 0x2870e5b2fc68778fb764e95856df36e33b9a035d0f272153fbff1ae617f8e4ee)
            mstore(add(m, 0x3c0), 0x0670b26e37198512d8bbbad096f695d1ed2fcc2bb40d15f51be87654eb9aa805)
            // s1
            mstore(add(m, 0x3e0), 0x1ce9a8d9c348106a8e704dc5e70f5db649fd4491bc79248659e34760f414198f)
            mstore(add(m, 0x400), 0x2311516dfff6cc7c20267bee5a1308571d7decda7daa5a279dbff25208f1271a)
            // s2
            mstore(add(m, 0x420), 0x00baa94d8b36420d18ddeec79f1a0231747db7c27ca570a775ce5c3147ced06b)
            mstore(add(m, 0x440), 0x111021cdbf9951878e2aeed3578d852e1c6c733420ef34f4e4677f9a182b647a)
            // s3
            mstore(add(m, 0x460), 0x2b5bcc8596800eb1779bb2de35b8e4f3991b33bd0620e0eb06f7ee44fd43c861)
            mstore(add(m, 0x480), 0x1f081c9fed7aa6a7f6313ec5878e3c8ef253282555624920fabeb0b7370357a9)
            // s4
            mstore(add(m, 0x4a0), 0x2306ac204981ba7d39a0fe3f33e52ada3c7f57b74c5ed3a724aa9a4a1db42a28)
            mstore(add(m, 0x4c0), 0x22a29e78fcbb13303c64020bc321fdf5daeb91d3e39ddde9330b9e06f6a3e967)
            // id1
            mstore(add(m, 0x4e0), 0x155d7f52bd2ed2c2dd1cba7f3c012b3b8b9afdbb4a900d71728addcee205b2e7)
            mstore(add(m, 0x500), 0x09fd70e220e315157fb55709dcace3059771ad5c39edb28d719869efb23ea889)
            // id2
            mstore(add(m, 0x520), 0x29151aa5232cb2ef588ecf554ed15f86f15779b6128a478fbd241c2b29e1b039)
            mstore(add(m, 0x540), 0x14e71ae01f20b63a94871bcf7fc00a7d6925678f8d2f9ed9f49d244a10371d92)
            // id3
            mstore(add(m, 0x560), 0x05b7eb02cfe5d261adc6e5d0ab5bcbc817c2430899388d8fd13870ec6cea1cc9)
            mstore(add(m, 0x580), 0x0f019f3e32f68c43d0c2ac24806311804faa1b7a4b7b7c88c4881a6c5f42dfb0)
            // id4
            mstore(add(m, 0x5a0), 0x3042d9993d8e8590200450e436da8919053181f6a3fc79a92e9c2042d223004e)
            mstore(add(m, 0x5c0), 0x0c130c1ede86d2b46c06a59e4d23c390ec6773c1802275f0e5468aae26361b8b)
            // t1
            mstore(add(m, 0x5e0), 0x0117ed333c8f7b65c9d52f5c2371c5c75fe69d4bf722eb517be7382eaffcb205)
            mstore(add(m, 0x600), 0x1a47a010417bdf8c0825bed565bd29e325ac8e6301427ffcbaf9e1790e8a29b7)
            // t2
            mstore(add(m, 0x620), 0x1c9c07dc8213c42d0f00c967b510e43d22c9a15e1413a27b0cf1f6e38264992b)
            mstore(add(m, 0x640), 0x0034d4b14d1cf84231ce71b6b4e558aab36e98fcde16ce45927a1ce2b30c7993)
            // t3
            mstore(add(m, 0x660), 0x25543785070c19ef752a9699d2d64b6677fc2f42648e30f171d5099f0819e9e0)
            mstore(add(m, 0x680), 0x2266b79c3483b16aace77a21be7ae9db092476aca4336f7b8fa8244017afa3fa)
            // t4
            mstore(add(m, 0x6a0), 0x1ebd743b2bb94ad54c579e0a45e199d98e660b1a7cd3468bb20305a9bf15c44f)
            mstore(add(m, 0x6c0), 0x1142f8a773d36ab7b120f4547469e93c71a76608e1a3540496e9ee4bf2dd67a3)
            // lagrangeFirst
            mstore(add(m, 0x6e0), 0x0000000000000000000000000000000000000000000000000000000000000001)
            mstore(add(m, 0x700), 0x0000000000000000000000000000000000000000000000000000000000000002)
            // lagrangeLast
            mstore(add(m, 0x720), 0x0fc01c961c66a0f2f6b430f0b6f9f45e43cce66658fa1e128462eb882259beb4)
            mstore(add(m, 0x740), 0x0eb23f4285bfba609651ad8a926325e9f297493e331d5c8b45c987f149c7aec5)

            // 59 words × 32 bytes = 1888 = 0x760
            return(m, 0x760)
        }
    }
}
